spring.application.name=restaurant-backend
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://Tomiraoka:TU12LE02SHEV2009@wanderly.xroyaig.mongodb.net/hostack?retryWrites=true&w=majority&appName=Wanderly}

app.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173,http://localhost:5174,http://localhost:3000}

logging.level.org.springframework.security=WARN
logging.level.com.restaurant=INFO
logging.level.org.mongodb.driver.cluster=WARN

spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.serialization.write-dates-as-timestamps=false

restaurant.delivery.accept-to-cook-minutes=1
restaurant.delivery.fallback-cook-minutes=10
restaurant.delivery.ready-to-courier-minutes=2
restaurant.delivery.courier-to-delivered-minutes=8
restaurant.delivery.scheduler-interval-ms=10000

restaurant.card.min-balance=50000
restaurant.card.max-balance=500000

restaurant.loyalty.bronze-orders=3
restaurant.loyalty.silver-orders=8
restaurant.loyalty.gold-orders=15
restaurant.loyalty.bronze-discount=5
restaurant.loyalty.silver-discount=10
restaurant.loyalty.gold-discount=15
